# Generated by Django 2.1 on 2020-12-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xapi2',
            new_name='xapi',
        ),
    ]
